### ISSUE TITLE
Improve Generator with this todo list

### ISSUE THREAD

**Issue by samuel-duhaime** [chairemobilite/evolution#394]
# Todo list

- [x] Add Generic widgets that we use in more than 2 surveys, so we can reuse the same logic, and the user always has the same experience.
- [x] Simplify the generatorConfigs.yaml: I don't need to ask for the output_file for each script, I can only ask one time for the output_folder location, and the script will always create the files in the same location.
- [x] Add types for Section and WidgetsNames
- [x] Add an Excel tab for HelpPopup.
- [x] #402
- [x] #406
- [x] #576
- [x] Add more tests
- [x] Add inputMapFindPlaceBase with Generator: New Excel tab with geoCodingQueryString and icon
- [x] Add custom validations for validations specific to the survey
- [x] #416
- [x] Find a way to add customPath for Radio Input
- [x] #415
- [x] #414
- [x] Update Generator Example with new configs and Excel
- [x] #423

**Comment by samuel-duhaime** [comment]
Okay, we finally did this issue. We can close. :)
