### ISSUE TITLE
Add UI testing in Evolution

### ISSUE THREAD

**Issue by samuel-duhaime** [chairemobilite/evolution#487]
# Issue

## Description
The goal is to incorporate UI testing directly into Evolution to streamline the testing process for every survey. We should use the code from MJ as a starting point.

## Justification
Automating UI testing reduces manual efforts required to verify changes made to surveys, ensuring efficient testing and reliable outcomes.

## Todo

- [x] #490
- [x]  Add a comprehensive Readme detailing setup and usage instructions.
- [ ]  Implement a function to retrieve interview data for test users, focusing on scenarios such as checking scenarioNumber.
- [ ]  Develop a function to modify interview data for test users, enabling scenarioNumber adjustments for testing purposes.
- [ ] #491
- [x]  Capture screenshots or videos during testing, particularly in case of failures, to aid in debugging.
- [x]  Support multiple testing scenarios, such as testing questions across various scenarios in the MJ survey.
- [x]  Utilize Generator for generating UI testing scenarios efficiently.
- [x]  Explore and integrate different methods for connecting to surveys to enhance testing versatility.
- [x]  Ensure comprehensive testing coverage for every question type to validate survey functionality.
- [x]  See if we can support a variety of browsers, including mobile and tablets

**Comment by tahini** [comment]
Screenshots can be configured from the playwright.config.ts file like this:
```
defineConfig({
   ...
   use: {
        // Base URL to use in actions like `await page.goto('/')`.
        baseURL: 'http://localhost:8080',
        // Collect trace when retrying the failed test.
        trace: 'on-first-retry',
        screenshot: 'only-on-failure'
    },
    ...
})
```
