### ISSUE TITLE
Refactoring (May 2024 planning reunion) - Technical Infrastructure and Data Flow

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/evolution#753]
# Description
Technical architecture modernization to support new features.

# Tasks
- [ ] Document existing architecture
- [ ] Design new data flows
- [ ] Implement REST APIs
- [ ] Set up monitoring
- [ ] Optimize performance

# Technical Sub-tasks
- API documentation
- Load testing
- Performance metrics
- Security and authentication

**Comment by kaligrafy** [comment]
![tableau_evolution](https://github.com/user-attachments/assets/f49617a0-4da1-4e21-a47a-8468b7933d36)

**Comment by kaligrafy** [comment]
![438271706_477608407952357_5983589449585402031_n](https://github.com/user-attachments/assets/93c57c2e-4245-4da6-814f-e915835248de)

**Comment by kaligrafy** [comment]
My thesis for datawarehouse:
https://publications.polymtl.ca/2116/1/2016_P%C3%AEerreLeoMongeonBourbonnais.pdf
